### ISSUE TITLE
[Item][Trinket] Soul Preserver proc gets affected by Tree of Life talent

### ISSUE THREAD

**Issue by Barcaz** [Stormforge-gg/Bugtracker-Fordring#1263]
**Description**: Recently discover really wierd bug about soul preserver cost reduction being 640 not 800 for resto druid, which is really massive downgrade for pre-bis trinket and here is the proof
![restoSoul](https://user-images.githubusercontent.com/51231110/173199198-3e04e312-00c4-4a6f-a13b-8426e04dee16.png)
I didn't have much ground or idea what could cause this, but i think i have really good lead about that. LIfebloom cost,because of the tree of life talent is 782 and with the proc it should drop to 0, but it does get reduced by 640 and 160 is exactly 20% of 800.
.
So in other to be sure i tested it in boomkin build without that talent. Here it is
![BoomkinSoul](https://user-images.githubusercontent.com/51231110/173199362-383118c2-20af-4410-80ab-f89b04e31362.png)
Without that talent lifebloom cost is 978 and it get reduced by 800 to 178 as it should be.

**Current behaviour**: So unless i'm wrong i think i have enough leads to assume that this 800 mana cost reduction gets affected and nerfed by the tree of life talent with 20% which shouldn't affected it by any case.

**Expected behaviour**: No talents should affected the 800 cost reduction of the trinket

**Comment by NatsumeLily** [comment]
Off-topic to the report. 
This trinket wouldn't be pre-bis, it looks ok but there are honestly better ones.

**Comment by Barcaz** [comment]
Like? If you use that trinket correctly its 75 spell power and 70-80 mp5 there is nothing even close to this. Even jetze bell falls a lot unless you are 100% mana efficient as its just 25 more sp but its mp5 proc is complete shit.

**Comment by NatsumeLily** [comment]
Spark of life would be top. Je'Tze's Bell is good. Forge ember is also really good. The sp is better in most cases, you won't really hit any mana problems. 

You'll end most fights at 70-85% mana.

**Comment by Barcaz** [comment]
You'll until some fights like sapp or kt taking 9min+ with enough tunning..And in 10m you are far from mana independent, but really depends on the tunning.Spark of Life/ Soul preserver gives you most bang for your bucks in general. Jetze may get slightly better only in full naxx bis.

**Comment by Wolffenstein** [comment]
The proc works correctly - the flat value of Soul Preserver is subtracted from the base cost of the spell and then multiplied by the percentage modifier
So if a spell costs 2000 mana, and you have Tree of Life talent and Healing Trance proc, the following formula will apply:
cost = (2000 - 800) * 0.8.

What you probably forgot to include in your calculations is the fact that the tooltip mana cost of your spells already has tree of life reduction included if you have the talent, so instead of 2000 it will show you 1600, which probably led you to believe your spell should cost 800 mana (1600-800) but ended up costing 960 ((2000 - 800) * 0.8), which would suggest Soul Preserver only saved you 640 mana.

**Comment by Barcaz** [comment]
Gotcha, my bad sorry for the misunderstanding.
