### ISSUE TITLE
[Spell][Shaman][Warrior] Thunderstorm

### ISSUE THREAD

**Issue by Nuy** [Stormforge-gg/Bugtracker-Fordring#1430]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Doesn't knock away people correctly (hard to knock someone off Blade's Edge bridge for some reason) and it can be reflected resulting in shaman getting knocked away what's not correct.

**Current behaviour**: Doesn't knock away people correctly (hard to knock someone off Blade's Edge bridge for some reason) and it can be reflected resulting in shaman getting knocked away what's not correct.

**Expected behaviour**: Should knock away people normally and can't be reflected.

**Revision**: 1535

**Comment by Godmatik** [comment]
According to this - being able to spell reflect Thunderstorm is intended.

https://www.mmo-champion.com/threads/624196-Thunderstorm-amp-Spell-Reflection
https://www.mmo-champion.com/threads/658630-Spell-reflect-and-elemental

**Comment by Nuy** [comment]
> According to this - being able to spell reflect Thunderstorm is intended.
> 
> https://www.mmo-champion.com/threads/624196-Thunderstorm-amp-Spell-Reflection https://www.mmo-champion.com/threads/658630-Spell-reflect-and-elemental

We're on 3.3.5 patch and these can be early Wrath bugs. Early WotLK was a mess in terms how many things worked and there were many bugs which got fixed later. Tried to find a video of shaman using Thunderstorm when warrior has Spell Reflection up but was unable to find one. What I know is that on every other server Thunderstorm goes through SR every time no matter what and comments from 3.0/3.1 retail patch aren't good proof for how thing should be in 3.3 patch.

**Comment by NatsumeLily** [comment]
> What I know is that on every other server

I was going to rip into you because of that comment. Which is such bullshit...

But you are correct. There is nothing about this change in patch notes but I found this...

https://www.mmo-champion.com/threads/680791-Fix-Spell-Reflect
![image](https://user-images.githubusercontent.com/15247730/174919646-e1b65fa5-1485-4511-a2ef-4940e37160ee.png)

https://www.mmo-champion.com/threads/702040-Favorite-Spell-to-Spell-Reflect/page2
![image](https://user-images.githubusercontent.com/15247730/174919696-22531394-128c-4d03-ba5f-2447e2020266.png)

Both of those comments are later in Wotlk and imply it was changed by Blizz.
