### ISSUE TITLE
[NPC][Eye of Eternity] Malygos vortex and interrupt stuff

### ISSUE THREAD

**Issue by NatsumeLily** [Stormforge-gg/Bugtracker-Fordring#1470]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: This was reported and "fixed".
![image](https://user-images.githubusercontent.com/15247730/175350968-8ed3e38a-5c16-4091-96db-05133856ace6.png)

**Expected behaviour**: This report and fix would be incorrect. 

https://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-general/wow-ui-macros-talent-specs/293632-holy-paladin-pve-guide-updated-3-3-a.html
![image](https://user-images.githubusercontent.com/15247730/175351187-fc693e35-2ffa-409d-9c53-7bde4757774c.png)

https://wowpedia.fandom.com/wiki/Malygos_(tactics)?oldid=2303594
![image](https://user-images.githubusercontent.com/15247730/175351466-04bfacda-31ec-4f8c-bace-e54fbb3e0698.png)

https://wowpedia.fandom.com/wiki/Concentration_Aura?oldid=2297427
![image](https://user-images.githubusercontent.com/15247730/175351592-ba8e566e-97ef-4c72-bcb3-b9832a5de7c6.png)

https://www.tentonhammer.com/guides/wow-guide-malygos
![image](https://user-images.githubusercontent.com/15247730/175351679-89c275ec-373c-4d65-9c6f-b1d08dd06b72.png)

**Revision**:

**Comment by haephaistoss** [comment]
That would mean using aura mastery you can cast while moving and that abomination is in cataclysm not in wotlk.

If you find a video from retail era showing this exact behaviour, I'd give you credit, but wowwiki has been proven to be unrealiable at times, and this doesn't seem to click.

Another wowwiki or wowfandom link said with 100% pushback reduction you can cast just free but that's bs as well, as it is not pushback, but movement that interrupts your casting.

**Comment by NatsumeLily** [comment]
> That would mean using aura mastery you can cast while moving and that abomination is in cataclysm not in wotlk.
> 
> If you find a video from retail era showing this exact behaviour, I'd give you credit, but wowwiki has been proven to be unrealiable at times, and this doesn't seem to click.
> 
> Another wowwiki or wowfandom link said with 100% pushback reduction you can cast just free but that's bs as well, as it is not pushback, but movement that interrupts your casting.
> 
> There is also a chance that it was bugged on blizz and nobody ever gave a fuck to fix it, like the VoA glitch, but that was patched out here as well.
> 
> I see no reason to further trivialize an already trivial fight honestly.

1. I did not link wowwiki.
2. Your character is not moving during vortex technically. https://youtu.be/HvPvWIEiUsk?t=155 - Ranged attacks work during vortex.
3. I have 4 fucking sources telling you that it should work, with all 4 being from wotlk era.

And not related to this report. What VoA glitch?

**Comment by haephaistoss** [comment]
Wowpedia is wowwiki who are we kidding...

I took a video showing that VoA glitch still works in Shadowlands (proved it's existence), but the answer was: if it's clear it that can be abused to circumvent game mechanics intended by blizzard it was gonna be patched out.

And this sir seems like you're campaigning to be able to circumvent and zerg a game mechanic.

Heigan on retail wotlk Naxx was easily soloable by a single prot paladin, yet it isn't here. Are you gonna report that too that it's too difficult and DMG numbers are not blizzlike? Because they aren't.

4 horsemen usual tactics include zerging the first 2 together in green heroic gear completely ignoring their mechanics.
Are you gonna argue that it's not fair that you can't do it here because if how they are tuned to provide a challenge?

Ppl didn't abuse that bug back in the day as much as they would today, completely trivializing the entire fight, losing interest pretty quickly.

**Comment by NatsumeLily** [comment]
Wowpedia is not wowwiki...

https://youtu.be/xYqJ-8FiXCI?t=57 the hunter is casting steady shot during vortex (and also getting push back). 

Mmm...Now how would that be possible while moving, because your character isn't moving during vortex.

Get out of here with your fucking bullshit and no fucking proof.

**Comment by Wolffenstein** [comment]
Reverted in rev 1560.
