### ISSUE TITLE
[SPELL] Taunt Effects don't put players in combat

### ISSUE THREAD

**Issue by haephaistoss** [Stormforge-gg/Bugtracker-Fordring#1621]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Taunts should cause combat and make eating 6 drinking targets to stand up, should even interrupt first aid.

no data on resurrection tho

**Current behaviour**: currently combat is not applied

**Expected behaviour**: 

**Revision**:

**Comment by ScottieDOESknow** [comment]
Taunts do not (and should not) cause combat vs other players because players are (and should be) immune to taunt.
I believe what you mean to report, is that Hand of Reckoning damage is not triggering combat for other players.

**Comment by haephaistoss** [comment]
No, that's not true.

Taunt effects should put players in combat, and cause them to stand up when eating/drinking/sitting in pvp combat.

**Comment by ScottieDOESknow** [comment]
> No, that's not true.
> 
> Taunt effects should put players in combat, and cause them to stand up when eating/drinking/sitting in pvp combat.

so in which which patch was that added?
you provided no source for your initial claim...

**Comment by haephaistoss** [comment]
wtf since taunt effects have been in the game and pvp is a thing you moron

**Comment by haephaistoss** [comment]
https://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-exploits/257608-hand-of-reckoning-usage-pvp.html

2008 ...

the fact that you have no idea how effects work is one thing but claiming false shit is a totally another level

**Comment by haephaistoss** [comment]
wrong image

**Comment by haephaistoss** [comment]
![Screenshot_20220715-022139_Brave](https://user-images.githubusercontent.com/67190649/179122462-f89f9c9d-7339-4176-8277-c766e3af6d13.png)

**Comment by haephaistoss** [comment]
most basic common knowledge ever

**Comment by ScottieDOESknow** [comment]
Everything you just linked is ONLY about Hand of Reckoning, which basically supports my statement that that is the only "taunt" that works in pvp vs PLAYERS.

So why does not Warrior Taunt work the same way? or Druid Growl? or DK Dark Command?

You can disprove this yourself easily. Go on any stock or fully progressed 1.12 vanilla client, TBC 2.4.3 client, TBC classic client, etc and none of what you claim is true at all. Taunt from warrior or druid does not work vs players at all. It does not prevent drinking. So hypothetically, let's say I am wrong, and all the above taunts DO work on wotlk client... then where is it in the patch notes? I just looked through every documented and undocumented changes for every wotlk patch 3.0 + and have not seen a shred of evidence to support your claim.

Furthermore, you can't expect a serious dev to make changes based on your word with no supporting evidence, that's _actually_ moronic. Posting some thread talking about HoR from a wow exploit website is not evidence to support your claim that ALL TAUNTS SHOULD PREVENT DRINKING.

If you actually believe that, then it's simply the fact that you're used to scuffed servers and you want it to be that way.
It does not work that way. 

Hand of Reckoning is the only "taunt" that effectively does this because it has a damage component to it. Even if the damage is non-existent or 1dmg it is still that component of the spell that puts a player in combat, not the taunt component.

**Comment by haephaistoss** [comment]
Growl even eats grounding totem by fucking hunter pets.

blizzard doesn't document all their changes and you can't find realizable latch notes in the internet.

furthermore I've collected a library of how stuff should work over a decade, and I've been with Tauri testing stuff before you even started playing wow.

I'm not here to post bullshit, simply copying stuff over from the closed tester githubs and closed forums if which you have no access.

simply making 1line statements, these all have been researched and fixed, they broke with db transfer prolly.

go test PvE

**Comment by ScottieDOESknow** [comment]
> Growl even eats grounding totem by fucking hunter pets.

BECAUSE ITS A SPELL

**Comment by haephaistoss** [comment]
every taunt is a spell, dk same way ...

even righteous defense omg

**Comment by ScottieDOESknow** [comment]
> Blizzard doesn't document all their changes

They do actually. You can even see every Undocumented Change from past patches.
![Screenshot 2022-07-14 204140](https://user-images.githubusercontent.com/43949261/179124145-fc96a977-7f35-4280-9440-a433b6330d09.png)

**Comment by haephaistoss** [comment]
I can name you a thousand things that are not in there... you're proven wrong, go home and let us testers do what we do so you can have a nice playing experience

**Comment by ScottieDOESknow** [comment]
> and I've been with Tauri testing stuff before you even started playing wow.

I started playing wow in 2005 on Original WoW Beta so not only are you wrong, but reaching.

**Comment by ScottieDOESknow** [comment]
I'm not going anywhere, Ill make a proper bug report for you since you are too stuck in your own head to do it yourself.
Cheers.

**Comment by haephaistoss** [comment]
and you expect me to believe you when you have no idea about basic spell interactions.... you are the exact reason alpha bugtrackers are not public

**Comment by ScottieDOESknow** [comment]
Swapping your argument from one fallacy to another changes nothing since my first reply. 

Show a video from _retail wotlk_ where warrior taunt, druid growl, dk dark command works on a player to keep them from drinking

**Comment by Godmatik** [comment]
What Scottie says is correct, taunt does not work on PvP players nor does it put them in combat, it does work on player pets/totems since they are not player characters. 

The only exception is Hand of Reckoning, because there is a damage component to it (in Wrath).

If Hand of Reckoning does not turn on combat currently then it is indeed a bug.

**Comment by haephaistoss** [comment]
i don't have to show you anything, you're nobody. Already did what we had to on the alpha and the first Iteration of Crystalsong, and it was fixed both times, it simply broke.

i don't have the time to do it a 3rd time with our old research deleted - you can nag at Chris maybe hell give us back the old forums but I doubt it.

**Comment by ScottieDOESknow** [comment]
> don't have to show you anything, you're nobody.

how many fallacies can you swap to
this is 5 now, lets get those numbers up

**Comment by haephaistoss** [comment]
https://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-exploits/209384-dark-command-trick-dk.html#post1367850

**Comment by haephaistoss** [comment]
every false claim you make can be proven wrong with the first result in Google man ... 😂

**Comment by haephaistoss** [comment]
seems like we found another exception, how interesting 🤔

**Comment by ScottieDOESknow** [comment]
I can find everything online to support my claims as well, exceptions included.
The difference is your claim is the one that must be proved _beyond a reasonable doubt_ because **you** made the initial claim.
How do you know it was not patched post Feb 2009 because that was a bug? You've never checked?

> I've collected a library of how stuff should work over a decade,

SURELY you can find ONE video from Season 8 that shows taunt/growl/dark command working in arena???

**Comment by haephaistoss** [comment]
i could, and I did now I'm simply not interested in doing it again with the original research gone, and doing it for the 3rd time. in 1 year gets old quickly.

should I prove to you that the sky is blue too?

this is common knowledge in circles where ppl are above 1800 rated, don't make yourself even more ridiculous 

you're not fixing it anyway, i don't even. know why I'm talking to you, you're just wasting my time

**Comment by ScottieDOESknow** [comment]
Your reliance on fallacy is absurd
were up to 6 now

show a video from S8 if you have a library of how stuff should work
I'm calling your bluff

**Comment by haephaistoss** [comment]
ok have fun, I'm done with your bs.

just swap your name to scottiedoesntknow, you're scamming ppl with this one

**Comment by ScottieDOESknow** [comment]
> should I prove to you that the sky is blue too?

https://www.youtube.com/watch?v=NafbGOQBlQs

![image](https://user-images.githubusercontent.com/43949261/179126859-bd5af1de-ffaf-483b-b907-aac5ed12a5da.png)

**Comment by Aithne99** [comment]
Reopen a better report with sources and without the flamewar please.
