### ISSUE TITLE
[Naxxramas][Tuning] Maexxna does less damage than before core switch

### ISSUE THREAD

**Issue by nikko8085** [Stormforge-gg/Bugtracker-Fordring#1646]
**Description**: Maexxna does about 20% less damage with all melee attacks compared to before the core swap.

**Current behaviour**: Maexxna is giving lovely nibbles

**Expected behaviour**: Maexxna should be biting your ass off

**Revision**: TC, 20220713

**Comment by Aithne99** [comment]
The thing about melee damages is that
1. I researched blizzlike values for our Naxx
2. Because most of them were about double of the TC values, we decided that the bullshit "custom tuning" (blech) should not apply to physical damage dealt by mobs, because in almost all cases they are already "buffed" (read: actually ballpark correct) compared to their previous iteration. IIRC Maexxna specifically will be slightly stronger elsewhere with our approach to """"""custom tuning"""""
