### ISSUE TITLE
[Profession] Skill ups in professions are not conform to previous core

### ISSUE THREAD

**Issue by Cheesedip** [Stormforge-gg/Bugtracker-Fordring#1771]
**Description**: 
You get +1 skill on green skill ups, +2 on yellow skill ups, +3 on orange skill ups. 
We should be getting +3 until lvl 400 and +1 after.

**Current behaviour**:
see description

**Expected behaviour**: 
see description

**Comment by BobSemple** [comment]
It seems the new core has other skill up rules for all: orange items/locks are +3 skill, yellow are +2, and green ones are +1. At least that's what I saw so far.

**Comment by Cheesedip** [comment]
This makes sense, I actually saw similar behaviour but couldnt understand why I got +2 one time and +1 the other but this makes sense. Lockpicking leveling is based on a lot of green skill ups so this is especially tedious now.

**Comment by TheRealestMcCoy** [comment]
Can Confirm this 


You create: [Runecloth Belt]. 
Your skill in Tailoring has increased to 269. 
You create: [Runecloth Belt]. 
Your skill in Tailoring has increased to 272. 
You create: [Runecloth Belt]. 
Your skill in Tailoring has increased to 274.

**Comment by Aithne99** [comment]
The expected point value is still three times as many as you'd gain with Blizzlike rules, it's just that there is a triple chance to gain points, and excess chance overflows into an extra point.

So with the previous rules, if you'd have a 25% chance to gain three points on a craft, here you'll have a 75% chance to gain one point instead. An 50% base chance turns into 150%, which means one guaranteed point and one extra point with 50% chance. This is done so that 1. non-whole multipliers like 3.3 also work with the profession bonuses if we want to tweak it slightly and 2. the variance in the number of crafts required is lower this way.

This is how the Alliance perk profession boost was implemented in our MoP core, and after people got used to it, the benefits of the system were quite apparent :)
