### ISSUE TITLE
shit server, fix seed

### ISSUE THREAD

**Issue by Xullu** [Stormforge-gg/Bugtracker-Fordring#1808]
**Current behaviour**: Seed of Corruption damage does not go off on the main target that the spell is applied on, only to the main targets surroundings. 

**Expected behaviour**: The seed of corruption should also damage the main target its applied on. If there's 2 mobs and I seed on one, then the seed damage should hit both of 2 mobs instead of just one of them. 

![image](https://user-images.githubusercontent.com/105716384/181019078-454b5afb-e9f2-4566-a50c-98c5fd3f72fd.png)
https://wowwiki-archive.fandom.com/wiki/Patch_3.3.0_(undocumented_changes)

**Comment by Godmatik** [comment]
The proof you link is from another private server, so that is irrelevant.

That being said - this seems correct. In TBC it only dealt damage to "other enemies" when it exploded, but the wording of the spell changed in Wrath, which seems to indicate it should damage the target itself as well. So if the explosion isn't doing damage to the seeded target, it is indeed a bug.

TBC tooltip
https://tbc.wowhead.com/spell=27243/seed-of-corruption#comments

"When the target takes 1044 total damage or dies, the seed will inflict 1110 to 1290 Shadow damage **to all other enemies** within 15 yards of the target"

WotLK tooltip
https://www.wowhead.com/wotlk/spell=27243/seed-of-corruption#comments

"When the target takes 1044 total damage or dies, the seed will inflict 1110 to 1290 Shadow damage **to all enemies** within 15 yards of the target.

**Comment by karserasl** [comment]
So pretty much reduced locks to spriests, but with a casttime..
Good core.

**Comment by Jocroy** [comment]
I only found this comment (I know, wowhead comments are not the most trustworthy source), that indeed suggests that SoC should damage the main target since patch 3.3 (which we are on in terms of class mechanics). But its a bit of a grey area, since it apparently had the current behaviour up to patch 3.3.

https://www.wowhead.com/spell=27243/seed-of-corruption#comments:id=942908

**Comment by adambcurrier** [comment]
The Burning Crusade Classic PTR, which is running the WotLK pre-patch, shows that Seed of Corruption does damage the primary target when it explodes.

![2022-08-08-000236](https://user-images.githubusercontent.com/108972597/183444043-589f727e-15af-4140-b0cf-fcbfb1d7eea5.png)
.

**Comment by karserasl** [comment]
> The Burning Crusade Classic PTR, which is running the WotLK pre-patch, shows that Seed of Corruption does damage the primary target when it explodes.
> 
> ![2022-08-08-000236](https://user-images.githubusercontent.com/108972597/183444043-589f727e-15af-4140-b0cf-fcbfb1d7eea5.png) .

Don't bother. They don't care enough.

**Comment by Godmatik** [comment]
Bump

**Comment by Godmatik** [comment]
Bump!

**Comment by Godmatik** [comment]
:(

**Comment by Iluvu-SF** [comment]
I highly recommend reopening this issue as the issue is not resolved.
@Godmatik 
@Xullu

**Comment by Drevil-Dion** [comment]
> The Burning Crusade Classic PTR, which is running the WotLK pre-patch, shows that Seed of Corruption does damage the primary target when it explodes.
> 

The reason it did that on TBC pre patch on classic is because classic uses the 3.3.5 talent for class balance

**Comment by adambcurrier** [comment]
> > The Burning Crusade Classic PTR, which is running the WotLK pre-patch, shows that Seed of Corruption does damage the primary target when it explodes.
> 
> The reason it did that on TBC pre patch on classic is because classic uses the 3.3.5 talent for class balance

So does Fordring.
