### ISSUE TITLE
Mace weapon skill stuck at 399

### ISSUE THREAD

**Issue by JaceEverwood** [Stormforge-gg/Bugtracker-Fordring#1885]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)
![image](https://user-images.githubusercontent.com/19348079/182196837-35d1c078-5627-4006-b7e3-ce1021f03b70.png) (leveling from before 400 seem to be working)

but some weapon skill just stuck at 399 for some reason:
![image](https://user-images.githubusercontent.com/19348079/182197241-b7d2f5cd-3919-47a0-b3f1-7c5d71ef695a.png)

**Description**: 
weapon skill level at a +3 per chance proc. but my mace skill seems to be stuck at 399 hitting stuff for over 8+ hours. I test dual wielding an axe (it was at 286 weapon skill) and a mace(399). by the time the axe skill got level to 400, the mace still stuck at 399.

**Current behaviour**:
unable to get to 400 weapon skill on mace weapon skill

**Expected behaviour**: 
it should be hitting 400 weapon skill after hours of hitting stuff

**Comment by Cold-Martijn** [comment]
Weapon skill ups, especially the last couple are very slow, slower than blizzlike. Can confirm that much atleast.

I don't think it has to do with the specific weapon skill.

**Comment by Exorcista** [comment]
Try the mobs in Blasted Lands (near the drak portal) the ones that cant die and leave your toon there afk white hitting, still 8hrs seems super bugged lol

**Comment by fondlez** [comment]
> Try the mobs in Blasted Lands (near the drak portal) the ones that cant die and leave your toon there afk white hitting, still 8hrs seems super bugged lol

If the core is Blizzlike at least in some ways, that won't work at all:

[Patch 3.0.8](https://wowwiki-archive.fandom.com/wiki/Patch_3.0.8) (2009-01-20): You can no longer skill up weapons on mobs that are immune to damage.

Wowwiki/wowpedia "Weapon Skill" section has some good suggestions:

- Primordial Drake Eggs in Sholazar Basin
- Vendors in Dalaran sell white, low DPS weapons with extremely low attack speeds, making them great options for levelling weapon skill
- solo Violet Hold normal. Do not start the event. Stay near the guards if you get into trouble
- *maybe* having Intellect buffs could increase the rate at which weapon skills are learned.

This core also permits weapon skill gain from at least one type of target dummy, though it may require you having to use yellow skills not just auto-attack.

Since I do not play melee, I have no practical idea if any of the above actually works on this core though ...
