### ISSUE TITLE
[Quest][Icecrown] Leading the Charge(13380) and Watts My Target(13381)

### ISSUE THREAD

**Issue by CosminPOP** [Stormforge-gg/Bugtracker-Fordring#298]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Both quests require you to hop on a bomber plane from Karen No
![image](https://user-images.githubusercontent.com/7255825/166999770-34d2e7d9-e87f-4a12-a562-cac6e44d7a8e.png)

**Current behaviour**:
You get a buff but the bomber doesnt arrive.
![image](https://user-images.githubusercontent.com/7255825/167000409-c0b630b0-a614-41f3-b623-f14719234763.png)

**Expected behaviour**: 
A bomber should arrive for you to get on and kill some mobs.
**Revision**: 
1094

**Comment by FX-SF** [comment]
1) Current Behavior confirmed: No bomber appears when requested from Karen No.
2) Unable to complete quest, even with melee combat and Beta Buffs. Appears bomber is necessary to complete quest.
3) A video from 2008 showing the quest: https://youtu.be/nnJMLBD4oHs?t=43
 Appears that, upon requesting a bomber from Karen No, the Expected Behavior is you are automatically put into a bomber.

**Comment by Exorcista** [comment]
Still bugged with same issues almost a month later

**Comment by aguczam** [comment]
still bugged month and 2 days later
