### ISSUE TITLE
[Talent][Paladin] Ardent Defender

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Fordring#567]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
![WoWScrnShot_051822_221904](https://user-images.githubusercontent.com/78314117/169189990-8e79f06a-d821-49b7-8530-8e8570569eb9.jpg)

It's possible to get one-shot and have Ardent Defender save your life but only give you 1 hp. I have 468 Defense right now, it should be much more than that. And, indeed, it was, most of the other times I tested. I had difficulty recreating this.

**Comment by haephaistoss** [comment]
Patch note:

Wrath of the Lich King Patch 3.2.0 (2009-08-04): Redesigned. Any damage that takes the paladin below 35% health is reduced. This reduction applies only to the portion that pushes the paladin below 35% health (example: a paladin at 50% health takes a 40% hit; the first 15% hits as normal while the next 25% is reduced). In addition, once every 2 minutes an attack that would have killed the paladin will fail to kill, and instead heal the paladin for up to 10/20/30% of maximum health depending on the paladin's defense rating (example: a paladin with defense equal to only 5 times his or her level will receive no healing from the talent, while a paladin who is immune to critical strikes from boss creatures through defense will receive the maximum amount).
Old was "Any damage taken by the paladin while at 35% health or below is reduced."

Healing portion should scale from 0 - 30% max hp based on Defense Skill, 400 or below meaning 0 and Boss Crit Immunity meaning 30% (maximum) scaling linearly in between.

540 is the cap, so 0% (400 or below) - 30% (540 Defense or above)

Also note, that the values should not be absolute, 400 def is 5 * Level, it should be level dependant.

This means that if defense skill is in the 0% healing range, the attack that would otherwise kill the paladin will fail to kill, any dmg that would be overkill minus 1 will be absorbed, including Chaos Bolt, and dmg with Sanctified Wrath active, but leave the paladin at 1 hp.

**Comment by Vishiswaz** [comment]
Okay then why did Ardent proc every single other time we tested this after and gave me 15% of my health back? Something is wrong.

**Comment by Vishiswaz** [comment]
So then me getting only 1% back was the bug

**Comment by Vishiswaz** [comment]
Not 1%, 1hp

**Comment by haephaistoss** [comment]
I feel like it has something to do the dmg absorbtion and healing part being separate spells and one having the CD based on the debuff it gives the other an internal one, and you only reset one with the command.

If not that then something's rly up and worth having a look into it.

**Comment by Vishiswaz** [comment]
As it shows in the screenshot, Ardent procced with no healing effect, just the damage reduction.

**Comment by Vishiswaz** [comment]
I also did not reset anything with any commands. No .cd, no .unaura

**Comment by haephaistoss** [comment]
the 15 % healing seems okayish tho, I'll look into it tonight and see what I can figure out.

the 9 hours time lag between us doesn't help xd

**Comment by Vishiswaz** [comment]
Yeah I agree, the 15% seems right. Not sure what happened in the instance with this screenshot. Had difficulty reproducing it.

**Comment by Vishiswaz** [comment]
Closing due to new server core.
