### ISSUE TITLE
[OBJECT] Battered Footlockers not respawning.

### ISSUE THREAD

**Issue by zinro** [Stormforge-gg/Bugtracker-Fordring#644]
**Description**: 
Battered Footlockers for Lockpicking in Stonetalon Mountains, Windshear Crag do not respawn.

**Current behaviour**:
Battered Footlockers for Lockpicking with requirement 70LP and 110LP do not respawn.

**Expected behaviour**: 
Other zones with same skill level Footlockers seem to spawn within 3-4 minutes

**Revision**: 
Waterlogged Footlockers (70LP) which are found underwater in Redridge Mountains, Lake Everstill spawn in a few seconds which I don't mind. The main thing being that Footlockers on land spawn in randomly withing an area, as Waterlogged ones have a static spawn points.

**Comment by Shulishin** [comment]
This also happens in Badlands, Angor Fortress, along with Ashenvale, Zoram Strand. I managed to find some lock boxes at the fortress (on mid/upper level/outside) that don't respawn. Only found one on Zoram Strand on the north west island, but likely someone previously going through this area just missed it.

Given this, a server restart (or crash) likely respawns these, so that's something at least.
