### ISSUE TITLE
Profession bonuses are wrong 

### ISSUE THREAD

**Issue by PolarCookie** [Stormforge-gg/Bugtracker-Fordring#802]
**Description**: 
The bonuses and spells from professions are tuned for epic gems in 3.2.
If you remove epic gems, without reverting the 3.2 buff, then you get the usual jank of BS being worth 2 blue gems, JC being worth 2 legendary gems and the rest being worth 2 epics.
See https://easyupload.io/bik4x8 for details

**Revision**: 
1294

**Comment by Vishiswaz** [comment]
Oh, I entirely forgot about this. This is a very common bug on private servers and is 100% not blizzlike.

**Comment by Vishiswaz** [comment]
I'm going to write up some examples. CURRENTLY EDITING THIS POST, DO NOT FIX THIS BUG REPORT YET

ENCHANTING:
Initially, the bonuses for enchanting were the following:
- [Enchant Ring - Stamina](https://wowwiki-archive.fandom.com/wiki/Enchant_Ring_-_Stamina)
- [Enchant Ring - Greater Spellpower](https://wowwiki-archive.fandom.com/wiki/Enchant_Ring_-_Greater_Spellpower)
- [Enchant Ring - Assault](https://wowwiki-archive.fandom.com/wiki/Enchant_Ring_-_Assault)

As you can see in the histories of these wowwiki articles, they were changed in Patch 3.2
- Enchant Ring - Stamina went from 24 Stamina per ring to 30 per ring (total of 48 => 60)
- Enchant Ring - Greater Spellpower went from 19 SP per ring to 23 SP per ring (total of 38 => 46)
- Enchant Ring - Assault went from 32 AP per ring to 40 per ring (total of 64 => 80)

The wowwiki is incorrectly saying these changes were in 3.1. [They were in 3.2](https://wowwiki-archive.fandom.com/wiki/Patch_3.2.0#Enchanting), as most profession changes were, due to the new, non-JC-only epic gems. 

JEWELCRAFTING:
The "Dragon's Eye" gems were given a boost in Patch 3.2 because of the introduction of epic gems, otherwise they lose value. The whole point of these gems were a Jewelcrafter stat bonus over normal gems. If normal, available-to-everyone gems get a buff, the Dragon's Eye gems are less of a bonus, unless they also are buffed.  Also, prior to patch 3.2, these items were "Prismatic" and could be put in any gem slot and contribute to the socket bonus. After 3.2, they gained a color identical to the non-epic gems of the same stat(s).

Here's a list of the changes:
- [Striking Dragon Eye](http://wowhead.com/?item=42142): Now +34 Strength (Before +27)
- [Shining Dragon Eye](http://wowhead.com/?item=36766): Now +68 Attack Power (was +54)
- [Luminous Dragon Eye:](http://wowhead.com/?item=42148) Now +34 Intellect (was +27)
- [Delicate Dragon Eye](http://wowhead.com/?item=42143): Now +34 Agility (was +27)
- [Flamboyant Dragon Eye:](http://wowhead.com/?item=42152) Now +34 from Stop Ind. (Was +27)
- [Fractured Dragon Eye](http://wowhead.com/?item=42153): Now +34 Armor Penetration (was +27)
- [Glossy Dragon Eye:](http://wowhead.com/?item=42146) Now +20 points mp5 (before +11)
- [Mystic Dragon Eye:](http://wowhead.com/?item=42158) Now +34 from Temple Ind. (Was +27)
- [Precise Dragon Eye: ](http://wowhead.com/?item=42154)Now +34 Expertise Ind. (Was +27)
- [Quick Dragon Eye](http://wowhead.com/?item=42150): Now +34 Ind. De haste (before +27)
- [Rigid Dragon Eye:](http://wowhead.com/?item=42156) Now +34 Hit Ind. (Was +27)
- [Runic Dragon Eye:](http://wowhead.com/?item=42144) Now +39 from Spell Power (was +32)
- [Smooth Dragon Eye:](http://wowhead.com/?item=42149) Now +34 Critical Hit Ind. (Was +27)
- [Solid Dragon Eye:](http://wowhead.com/?item=36767) Now +51 Stamina (was +41)
- [Sparkling Dragon Eye:](http://wowhead.com/?item=42145) Now +34 Spirit (was +27)
- [Storm Dragon Eye:](http://wowhead.com/?item=42155) Now +43 from Spell Penetration (was +35)
- [Subtle Dragon Eye:](http://wowhead.com/?item=42151) Now +34 from Ind. De Dodge (before +27)
- [Thick Dragon Eye:](http://wowhead.com/?item=42157) Now +34 Defense Ind. (Was +27)

BLACKSMITHING:
Not changed because their bonus scales with the gem changes in 3.2 by nature of being extra sockets.

LEATHERWORKING:
Here's a list of the changes, patch 3.2:
- [Arcane Resistance Fur Lining](http://wowhead.com/?spell=57701) now increases your arcane resistance by 70 points. (Instead of 60 points)
- [Attack Power Fur Lining](http://wowhead.com/?spell=57683) now increases your Attack Power by 130 points. (Instead of 114 points)
- [Fire resistance Fur lining](http://wowhead.com/?spell=57692) now increases your fire resistance by 70 points. (Instead of 60 points)
- [Frost Resistance Fur Lining](http://wowhead.com/?spell=57694) now increases your resistance to frost by 70 points. (Instead of 60 points)
- [Nature resistance Fur lining](http://wowhead.com/?spell=57699) now increases your resistance to nature by 70 points. (Instead of 60 points)
- [Shadow resistance Fur lining](http://wowhead.com/?spell=57696) now increases your resistance to nature by 70 points. (Instead of 60 points)
- [Spell Power Fur Lining](http://wowhead.com/?spell=57691) now increases your spell power by 76 points. (Instead of 67 points)
- [Stamina Fur Lining](http://wowhead.com/?spell=57690) now increases your stamina by 102 points. (Instead of 90 points)

ENGINEERING:
Here's a list of the stat-based changes, patch 3.2:
- [Mind Amplification Dish](https://wowwiki-archive.fandom.com/wiki/Mind_Amplification_Dish) added
- [Nitro Boosts](https://wowwiki-archive.fandom.com/wiki/Nitro_Boosts) crit rating increased from 16 to 24
- [Hand-Mounted Pyro Rocket](https://wowwiki-archive.fandom.com/wiki/Hand-Mounted_Pyro_Rocket?so=search) Fire damage increased to 1654 to 2020 from 1440 to 1760. Cooldown lowered to 45 seconds from 1 minute.
- [Hyperspeed Accelerators](https://wowwiki-archive.fandom.com/wiki/Hyperspeed_Accelerators?so=search) increased effect from 10 seconds to 12 seconds.
- [Reticulated Armor Webbing](https://wowwiki-archive.fandom.com/wiki/Reticulated_Armor_Webbing?so=search) armor bonus increased from 800 to 885.
- [Flexweave Underlay Agility](https://wowwiki-archive.fandom.com/wiki/Flexweave_Underlay?so=search) bonus increased to 23 (up from 15)
- [Springy Arachnoweave](https://wowwiki-archive.fandom.com/wiki/Springy_Arachnoweave?so=search) now increases spell power by 27 points (was 15)


ALCHEMY:
This one's a bit harder to research, sorry! Doing what I can. Also doesn't help that flasks were buffed in 3.1 for unrelated reasons I don't think we should bother with implementing. The 3.2 changes are what matter.

Mixology was buffed in 3.2. Here's the changes I could find:
- Mixology initially increased the HP bonus of Flask of Stoneblood from 1300 to 1620 
- Mixology initially increased the AP bonus of Flask of Endless Rage from 
- Mixology initially increased the MP5 bonus of Flask of Pure Mojo from 
- Mixology initially increased the SP bonus of Flask of the Frost Wyrm from 

Source for initial bonuses (the base values were buffed in 3.1 so I updated those, [but the _bonuses from Mixology_ were not buffed until 3.2](https://www.wowhead.com/forums/topic/flask-of-stoneblood-87647))
![image](https://user-images.githubusercontent.com/78314117/170835308-584a72f1-1242-47c0-ba97-a212150aab21.png)
https://www.wowhead.com/spell=53042/mixology#comments:id=596601

Source for after 3.2 values:
![image](https://user-images.githubusercontent.com/78314117/170834899-ade2a6fb-2a46-47ee-869b-af76e21e9e57.png)
https://www.wowhead.com/spell=53042/mixology#comments:id=884872

**Comment by PolarCookie** [comment]
https://docs.google.com/spreadsheets/d/1aMw40lztWlI8CbF7cO_AdzknbbzVzmPbzy-CcPYGOv8/edit?usp=sharing

better?

**Comment by Vishiswaz** [comment]
I'm doing all the research now and providing proof as well. This will help me make it. Thanks!

**Comment by Vishiswaz** [comment]
Done updating that post. Should have all the details.

I spoke with Wolf and he says he's holding off on implementing this for now. But if he ever does decide to do it, the post is ready to make things easier for him.
