### ISSUE TITLE
Chest open bug

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Fordring#952]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
If Player A starts to loot a chest and the cast isn't done, and Player B starts to open the chest before it opens. Player A doesn't remove all the loot, then leaves. This causes the chest to bug out, not properly despawn or respawn, and get stuck in an "open" position.

**Comment by Vishiswaz** [comment]
Leaving the area and coming back makes it lootable again.

**Comment by Nash124** [comment]
In general it seems that chests do not disappear in dungeons after being looted by someone else (at least thats what I noticed in all low level dungeons). Once someone else loots the now empty chest it, it disappears (or maybe it disappears only for the one that opens the empty chest).

**Comment by Vishiswaz** [comment]
Nash what you are referring to is something else entirely.

Your bug is caused by there being an item in the chest that the group needs to roll for, and if the person looting the chest leaves before the item is won and given to the winner, the chest doesn't despawn, even though it then is empty.

**Comment by AgentMalice** [comment]
To be more specific:

Any chest that a bosses uses to distribute loot is having this bug.  This include Four Horsemen, Eye of Eternity, Malganis in CoS, and others.  Should people open the chest at the same time it becomes un-openable by anyone else who tries after this moment.  When these first people leave the loot box or even the room can the late comers open it.  HOWEVER, sometimes this does not work and some late comers must alt+f4 or leave the raid/dungeon and re-enter to be able to open the chest.  And even then everyone must open it 1 at a time.

In dungeon like CoS or Oculus it is worse.  Should the person whom loots the chest leave group without closing the window, but winning an item from the roll, it can force others to never get the emblems.

I think the only solution is fixing the looting problem and auto distributing emblems upon boss death instead of in the chest.

**Comment by Vishiswaz** [comment]
Closing due to new server core.
